#!/bin/bash

readonly ASPECT_RATIO_REGEX='([0-9]+)x([0-9]+)'
readonly LOG_FILE='/var/log/autotiling.log'

log() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> "$LOG_FILE"
}

update_split() {
    local output window_width window_height
    if output=$(xdotool getwindowfocus getwindowgeometry 2>/dev/null); then
        if [[ $output =~ $ASPECT_RATIO_REGEX ]]; then
            window_width=${BASH_REMATCH[1]}
            window_height=${BASH_REMATCH[2]}
            if ((window_width > window_height)); then
                i3-msg 'split h' || log 'Failed to split horizontally'
            else
                i3-msg 'split v' || log 'Failed to split vertically'
            fi
        fi
    else
        log 'Failed to get window geometry'
    fi
}

if ! pidof i3 >/dev/null; then
    log 'i3 is not running, exiting'
    exit 1
fi

while read -r _; do
    layout=$(i3-msg -t get_tree | awk -F'"' '/focused/ {f=$4} /layout/ && f {l=$4} END {print l}' RS=,)
    if [[ $layout == 'splith' || $layout == 'splitv' ]]; then
        update_split
    fi
done < <(xprop -spy -root _NET_ACTIVE_WINDOW)

trap 'log "Received signal, exiting"; exit' INT TERM
