#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu appkill
#======================================================================#

# Colors
background="#282a36"
currentline="#44475a"
selection="#44475a"
foreground="#f8f8f2"
comment="#6272a4"
cyan="#8be9fd"
green="#50fa7b"
orange="#ffb86c"
pink="#ff79c6"
purple="#bd93f9"
red="#ff5555"
yellow="#f1fa8c"
forealt="#bfbfbf"
backtransp="#282a36CC"

# Style
lines="20"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $comment -nb $background -sb $comment -sf $background -fn $font"

# kill process
process=$(ps -A | dmenu -i -p "Type to search ▶" $theme | awk {'print $1'})
kill -9 $process 2>/dev/null
