#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu appkill
#======================================================================#

# Colors
background="#353535"
foreground="#EEEEEC"
critical="#15539E"

# Style
lines="20"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $foreground -nb $background -sb $critical -sf $foreground -fn $font"

# kill process
process=$(ps -A | dmenu -i -p "Type to search ▶" $theme | awk {'print $1'})
kill -9 $process 2>/dev/null
