#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu cycle menu
#======================================================================#


# Theme
source $(dirname "$0")/style

class=$(i3-msg -t get_tree | \
	egrep -o "(class\":\".[^\"]+)" | \
    sed '/i3bar/d;s/class":"//g' | dmenu -i -p "Jump to an application ▶" $theme) 
    
i3-msg [class="$class"] focus 2>/dev/null
