#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu commander
#======================================================================#


# Colors
background="#353535"
foreground="#EEEEEC"
critical="#15539E"

# Style	
lines="50"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $foreground -nb $background -sb $critical -sf $foreground -fn $font"

class=$(i3-msg -t get_tree | \
	egrep -o "(class\":\".[^\"]+)" | \
    sed '/i3bar/d;s/class":"//g' | dmenu -i -p "Choose an application ▶" $theme) 
    
i3-msg [class="$class"] focus 2>/dev/null
