#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu find
#======================================================================#

# Colors
background="#282a36"
foreground="#6272a4"
critical="#bd93f9"

# Style
lines="20"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $foreground -nb $background -sb $foreground -sf $background -fn $font"

# Find a file
find ~ | sed -e "s/'/\\\'/g" -e 's/\ /\\ /g' | sort -f | dmenu -i -p "Type to search ▶" $theme | xargs -r xdg-open

