#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu power-off menu
#======================================================================#

# Colors
background="#353535"
foreground="#EEEEEC"
critical="#15539E"

# Style
lines="3"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $foreground -nb $background -sb $critical -sf $foreground -fn $font"

# Power-off menu

OPT=$(echo -e " Logout\n Reboot\n Poweroff" | dmenu -i -p "Power menu ▶" $theme )

case $OPT in
	" Logout") i3-msg exit ;;
	" Reboot") systemctl reboot ;;
	" Poweroff") systemctl poweroff ;;
	*) ;;
esac
