#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	show i3 keyboard shortcuts
#======================================================================#

# Colors
background="#282a36"
currentline="#44475a"
selection="#44475a"
foreground="#f8f8f2"
comment="#6272a4"
cyan="#8be9fd"
green="#50fa7b"
orange="#ffb86c"
pink="#ff79c6"
purple="#bd93f9"
red="#ff5555"
yellow="#f1fa8c"
forealt="#bfbfbf"
backtransp="#282a36CC"

# Style
lines="20"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $comment -nb $background -sb $comment -sf $background -fn $font"

# Define the file path and name
FileName=~/.config/i3/config

# Perform several substitutions and display the output
grep 'bindsym $mod' $FileName | sed 's/bindsym //g' | sed -e 's/^[ \t]*//' | dmenu -i -p "Type to search ▶" $theme
