#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	show i3 keyboard shortcuts
#======================================================================#

# Colors
background="#282a36"
foreground="#6272a4"
critical="#bd93f9"

# Style
lines="20"
font="FontAwesome-12"

# Theme
theme="-l $lines -nf $foreground -nb $background -sb $foreground -sf $background -fn $font"

# Define the file path and name
FileName=~/.config/i3/config

# Perform several substitutions and display the output
grep 'bindsym $mod' $FileName | sed 's/bindsym //g' | sed -e 's/^[ \t]*//' | dmenu -i -p "Type to search ▶" $theme
