format = """
[](#888b8b)\
[  ](bg:#888b8b fg:#232729)\
[](bg:#215d9c fg:#888b8b)\
$directory\
[](fg:#215d9c bg:#888b8b)\
$git_branch\
$git_status\
[ ](fg:#888b8b)\
"""
# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "fg:#ffffff bg:#215d9c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#888b8b"
format = '[[ $symbol $branch ](fg:#232729 bg:#888b8b)]($style)'

[git_status]
style = "bg:#888b8b"
format = '[[($all_status$ahead_behind )](fg:#232729 bg:#888b8b)]($style)'
