format = """
[](#818181)\
[  ](bg:#818181 fg:#212124)\
[](bg:#0f52ba fg:#818181)\
$directory\
[](fg:#0f52ba bg:#818181)\
$git_branch\
$git_status\
[](fg:#818181)\
"""

[directory]
style = "fg:#ffffff bg:#0f52ba"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#818181"
format = '[[ $symbol $branch ](fg:#212124 bg:#818181)]($style)'

[git_status]
style = "bg:#818181"
format = '[[($all_status$ahead_behind )](fg:#212124 bg:#818181)]($style)'
