#======================================================================#
#	 __     ___  __      __   __   __   ___  __  
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__) 
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \ 
#	
#	my starship configuration file                                             
#======================================================================#

format = """
[](#ffffff)\
$username\
[](bg:#0f52ba fg:#ffffff)\
$directory\
[](fg:#0f52ba bg:#ffffff)\
$git_branch\
$git_status\
[ ](fg:#ffffff)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#ffffff"
style_root = "bg:#ffffff"
format = '[  ]($style)'

[directory]
style = "bg:#0f52ba"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "[ … ]"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#ffffff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffffff"
format = '[$all_status$ahead_behind ]($style)'
